version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_app
    container_name: laravel_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: bitzen
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432" # Mapeia a porta 3307 do host para a porta 3306 do contêiner
    volumes:
      - dbdata:/var/lib/postgres
    networks:
      - laravel
  # Serviço do Nginx
  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - laravel

  # Defina aqui outros serviços como banco de dados, Redis, etc.

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
    driver: local